### ISSUE TITLE
Camelize asks different in Rails 4.1

### ISSUE THREAD

**Issue by sasharevzin** [biola/rack-cas#35]
In configurations for `session_store.rb` we have to do something lile:
```ruby
require 'rack-cas/session_store/rails/active_record'
YourApp::Application.config.session_store :rack_cas_active_record_store
````
but then it threw NameError in rails 4.0.2:

```
gems/railties-4.1.10/lib/rails/application/configuration.rb:151:in `const_get': uninitialized constant ActionDispatch::Session::RackCASActiveRecordStore (NameError)
```

Rails takes hash (https://github.com/rails/rails/blob/4-0-stable/railties/lib/rails/application/configuration.rb#L144) and uses `camelize` method to get  `RackCASActiveRecordStore` but it defined as `RackCasActiveRecordStore` in file:
https://github.com/biola/rack-cas/blob/master/lib/rack-cas/session_store/rails/active_record.rb#L6

So `'rack_cas_active_record_store'.camelize` gives:
Rails 4.0.2: "RackCasActiveRecordStore" 
Rails 4.1.10: "RackCASActiveRecordStore" 

To fix it I used:
`YourApp::Application.config.session_store ActionDispatch::Session::RackCasActiveRecordStore` in my session_store file.

So maybe we can just update README file and we are good? :)

**Comment by adamcrown** [comment]
Hmm, this is strange. In my tests I show that both versions of activesupport camelize strings the same way. I've always had it as `RackCasActiveRecordStore` because that's the way camelize should work.

That being said I see no harm in modifying the README. I'll go ahead and make that change. Maybe it will help somebody out.

Thanks for the detailed description by the way.
