### ISSUE TITLE
Using rack-cas in Sinatra

### ISSUE THREAD

**Issue by Lucas-Quintana** [biola/rack-cas#47]
Hi!
I'm trying to include Rack-CAS in a sinatra application. We were using RubyCAS-Client but we want to change it.
I include Rack-CAS to a simple sinatra application before doing it in my real app and it works just fine.
The difference between the real app and the simple one or the examples in other issues is that we are using Sequel and the `request.session` hash is no loaded.
When I print  `request.session` in the console I get:
`#<Rack::Session::Abstract::SessionHash:0x155980927f40 not yet loaded>`
Because of that I'm getting a redirection loop because my app could not read it. Is there any chance to have a solution similar to the one for Rails and ActiveRecord? Sequel implements the same pattern.

Other difference we have is that we're also using `Shield::Middleware` and Shield work with the 401 Unauthorized.

I don't be able to establish wich gem is causing trouble (or both)

Any ideas?

Thanks for all

Best Regards, 
Lucas

**Comment by adamcrown** [comment]
Without seeing the code I'd say that both the session `not yet loaded` thing and `Shield:Middleware` seem suspect to me.

I don't know if you've seen the example Sinatra App that is linked to from the README but it uses the following line to initialize the session. You might try that.

```ruby
use Rack::Session::Cookie, key: 'rack.session', path: '/', secret: '...'
```

I was not familiar with `Shield` but after looking into it at a cursory level, it definitely does seems like it would cause problems since they're both trying to catch 401 responses. You may have to either not use `Shield::Middleware` or fork and hack both `Shield::Middleware` and `Rack::CAS` to look for a custom header in addition to the 401 status. Then make your application uses the appropriate headers in the appropriate places.

**Comment by Lucas-Quintana** [comment]
Thank You Adam!
I gonna check and write back if I find a solution!

**Comment by adamcrown** [comment]
I haven't heard back from this issue in a while so I'm going to close it. Please let me know if it's still an issue so I can reopen it. Thanks.
