### ISSUE TITLE
rails and excluded paths

### ISSUE THREAD

**Issue by dsusco** [biola/rack-cas#55]
Just a question here.

I have a `force_login` method that I'm using as a before filter on the actions that need it, I usually just put it over the entire app in my application controller. It looks something like this:

    unless (session['cas'] and session['cas']['user'])
      render status: :unauthorized, text: 'Redirecting to CAS sign in...'
    end

If I'm using the `exclude_path` or `exclude_paths` options, rack-cas kicks back requests that are excluded and I'm left with just a page saying "Redirecting to CAS sign in...". To get around that I can add logic in my app that replicates this: https://github.com/biola/rack-cas/blob/450916825d6151dcafb9dab8ece38fae85d43887/lib/rack/cas.rb#L19

I.e., it only checks for a valid session if the path is not excluded. But that seems redundant, since rack-cas is doing it anyway. Is there a better way to go about this? Say, catch what rack-cas kicks back and render the original request rather than the 401?

I'm guessing not, and that I have to replicate the logic in my app, as rack-cas needs the 401 to be passed the request in the first place.

**Comment by adamcrown** [comment]
Could you give me a bit more context as to why you need to exclude paths? The reason that feature was added was to support APIs since they should be able to return a 401 without it triggering an authentication redirect.

If you need to exclude paths for normal HTML pages I'd say just don't call your `force_login` method in those controllers or actions. Or you can implement your own path check in your `force_login` method. If you don't raise a 401, then rack-cas will just pass the response along without intercepting it.

**Comment by dsusco** [comment]
> I'd say just don't call your force_login method in those controllers or actions

Ya, that's what I'm leaning towards. I just thought it would be more convenient (read: I can be lazy) to throw the `force_login` over the entire app and just specify where to ignore it in a config file. Understanding what the option is actually used for cleared things up too, thanks.

**Comment by adamcrown** [comment]
You can always add `force_login` to your application controller as a `before_action` and then use `skip_before_action` on those few controllers you don't need to be authenticated too.
