### ISSUE TITLE
How can we exclude certain requests like /issues.json from cas authentication?

### ISSUE THREAD

**Issue by Aisha1994** [biola/rack-cas#85]

**Comment by adamcrown** [comment]
Hi @Aisha1994, sorry about the late reply to this.

`rack-cas` only kicks in if you return a response with a `401` status. So it would be up to you to exclude your `/issuse.json` endpoint from rendering a `401` response.

If you want to return a `401` response and have `rack-cas` ignore it so that it will render to the user, then there is a section of the README devoted to [configuring excluded paths](https://github.com/biola/rack-cas#excluding-paths).
